### ISSUE TITLE
Create interfaces/types for objects

### ISSUE THREAD

**Issue by stevenzeck** [stevenzeck/issue-complete#7]
* Interface for the config, build here:  https://github.com/szeck87/issue-complete/blob/graphql-typescript/src/ConfigBuilder.ts

**Comment by Divy123** [comment]
Hey! I want to take this issue.Can you please help me in this?

**Comment by stevenzeck** [comment]
@Divy123 sure.  I haven't done much here lately, been waiting for more GraphQL support from GitHub.
