### ISSUE TITLE
Running npm test produces error.

### ISSUE THREAD

**Issue by VANKINEENITAWRUN** [stevenzeck/issue-complete#8]
$ npm test

> issue-complete@1.1.0 test /home/tawrun/work/opensource/issue-complete
> jest && standard

 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins
      
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.613s, estimated 5s
Ran all test `suites.`
npm ERR! Test failed.  See above for more details.

**Comment by stevenzeck** [comment]
@VANKINEENITAWRUN Please retest with the latest changes.
